# fly.toml app configuration file generated for raiderio-discord-bot on 2023-09-15T20:33:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "raiderio-discord-bot"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[processes]
  web = "bundle exec rackup -p 8080"
  worker = "bundle exec ruby bot.rb"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
